### ISSUE TITLE
Fazer brand board

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#15]

**Comment by dilepego** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/1625a284-d835-420a-a6fd-f42bb2129496)

**Comment by dilepego** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/905e0576-76c5-4ae2-8eec-98d873f70897)

**Comment by dilepego** [comment]
![Desktop - 3](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/3a166326-74cb-4b42-8437-b544dabfd64f)

**Comment by dilepego** [comment]
![Desktop - 3 (1)](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/46cb64e6-0423-431a-a8f1-90f601cb5986)
Brand board feito
