### ISSUE TITLE
Fazer esboço da página principal (home) - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#18]
No figma, continuar o esboço anteriormente feito por Diego para a página principal. Nessa fase, façam somente marcações de espaço e alinhamento para termos uma ideia de como a página irá ficar. Após isso, colocar os dois esboços (mobile e web) no pages "Página principal", conforme definimos na reunião do dia 17/04.

**Comment by dilepego** [comment]
![issuegithub](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/d9f2833b-b41a-4831-9b2c-917905d8d9e4)

**Comment by dilepego** [comment]
![P](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/907ceed2-12e4-4e42-a5a4-16379e06be04)
