### ISSUE TITLE
Fazer esboço da página de cadastro - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#19]
No figma, fazer o esboço tanto mobile quanto web da página de cadastro. Após isso, adicioná-las na pages "Página de cadastro".

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/402d261c-b9eb-49ce-b356-6cc0903da7ba)
