### ISSUE TITLE
Refinar páginas principais - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#22]
Ajustar e melhorar as páginas conforme discutimos na reunião.

**Comment by dilepego** [comment]
![MacBook Pro 16_ - 1](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/e4c5ec1c-3ee4-4d3d-8bf2-435650a40433)
![Captura de tela 2024-04-26 170146](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/2a92cdad-422c-46fe-b365-501cfbf98775)
