### ISSUE TITLE
Refinar páginas de cadastro - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#23]
Ajustar e melhorar as páginas conforme discutimos na reunião.

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/09126ac2-9c20-4d90-8528-5b5613a19054)

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/7a7fd6cf-5300-4019-9ea9-155ef35ee03d)
