### ISSUE TITLE
Fazer esboço da página de login - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#30]

**Comment by lucasbrito0611** [comment]
No figma, fazer o esboço tanto mobile quanto web da página de login. Após isso, adicioná-las na pages "Página de login".

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/c865239a-4bb0-4fec-a1b5-38238db0b796)
