### ISSUE TITLE
Fazer esboço da página de perfil - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#31]
No figma, fazer o esboço tanto mobile quanto web da página de perfil. Após isso, adicioná-las na pages "Página de perfil".

**Comment by dilepego** [comment]
![Screenshot_20240428_180416_Figma.jpg](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/f62fd665-52fa-4610-9527-114df93dbf71)

![Screenshot_20240428_180432_Figma.jpg](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/28391fbf-0b82-4adc-b6ac-788f1dab7048)
