### ISSUE TITLE
Fazer esboço da página de Meus Pedidos - mobile e web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#34]
No figma, fazer o esboço tanto mobile quanto web da página de Meus Pedidos. Após isso, adicioná-las na pages "Página de Meus Pedidos".

**Comment by dilepego** [comment]
![Meuspedidos](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124363859/9e49a94c-5ca8-44d4-9b4a-74ebf637e034)
