### ISSUE TITLE
Fazer o esboço da página de "Promoções" - Web

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#41]
Fazer o esboço da página Promoções no figma para que, na próxima segunda, dia 15/07, a gente discuta possíveis mudanças e assim concluir essa página.

**Comment by dilepego** [comment]
![image](https://github.com/user-attachments/assets/d2c08562-9123-41f9-aa81-930cda50b009)
