### ISSUE TITLE
Definir as logomarcas para o projeto

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#5]
Definir 4 logomarcas com uma identidade visual para a marca. Duas logomarcas curtas, uma clara e uma escura. Duas logomarcas longas, uma clara e uma escura.

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/5d91766d-0db1-43cc-b3a3-c2aa11f7db90)
