### ISSUE TITLE
Fazer pop up da página de "Ajuda"

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#52]

**Comment by davidmtg** [comment]
![image](https://github.com/user-attachments/assets/7bd4a519-bfbb-490c-abd5-f694cde13c27)

**Comment by davidmtg** [comment]
![image](https://github.com/user-attachments/assets/f7e96e04-1d46-4996-b00f-1a9d5e1e557a)
