### ISSUE TITLE
Fazer o pop up de "Esqueceu a senha"

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#53]

**Comment by davidmtg** [comment]
![image](https://github.com/user-attachments/assets/f9754fb6-c822-4b5f-bcff-d49b43e67c40)

**Comment by davidmtg** [comment]
![image](https://github.com/user-attachments/assets/3c381f5b-6bb7-412c-a1c0-6208350b20db)

**Comment by davidmtg** [comment]
![image](https://github.com/user-attachments/assets/63bb17a5-8168-4431-944b-29fdc2cb4b1a)
