### ISSUE TITLE
Fazer o pop up de confirmação de Excluir Conta

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#55]

**Comment by dilepego** [comment]
![image](https://github.com/user-attachments/assets/6e57d19e-3b6c-42c1-82bc-d70de56b8354)

**Comment by davidmtg** [comment]
![image](https://github.com/user-attachments/assets/6be6e759-a825-4531-80e2-8d7bc122ee0e)
