### ISSUE TITLE
Fazer pop up de Editar Cartão

### ISSUE THREAD

**Issue by lucasbrito0611** [PI-InfoWeb-CNAT/2024-suplementos#59]

**Comment by dilepego** [comment]
![image](https://github.com/user-attachments/assets/b2508aba-3cc6-4128-aa7d-c641e89d395b)

**Comment by dilepego** [comment]
![image](https://github.com/user-attachments/assets/f251e6a0-7e63-4c7f-84c9-058ef5dff26e)

**Comment by dilepego** [comment]
![image](https://github.com/user-attachments/assets/f5abb698-ffb4-4755-82c3-ed5e422a771e)
