### ISSUE TITLE
Refinar as logomarcas para o projeto

### ISSUE THREAD

**Issue by leonardo-minora** [PI-InfoWeb-CNAT/2024-suplementos#9]

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/ab8c0a23-3117-4b76-a658-d8ded065e77b)

**Comment by davidmtg** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/124364476/312efe28-3178-489f-9ae6-fff998d57f0f)

**Comment by lucasbrito0611** [comment]
![image](https://github.com/PI-InfoWeb-CNAT/2024-suplementos/assets/122239789/b0bd2a78-28c0-438b-96ff-08e53aca7935)
